#!/usr/bin/python
#Script para la comprobacion de conexion a repositorio.

from nuxeoautomation import Client
import commands
import smtplib, email, time
from urllib2 import HTTPError
import socket
import sys
import os

#Datos de conexion al repositorio

nuxeo_url = sys.argv[1]
usuario = sys.argv[2]
password = sys.argv[3]

#Conexion con el repositorio

nuxeo = Client(nuxeo_url)
session = nuxeo.getSession(usuario,password)
try:
        session.getChildren("/")
        print "Repositorio OK"
except:
        print "Error al conectar al repositorio."
        sys.exit(2)
sys.exit(0)

